[package]
name = "snp-verifier-host-crypto-test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
asn1-rs = "0.7.1"
clap.workspace = true
hex.workspace = true
openssl.workspace = true
serde.workspace = true
serde_json.workspace = true
sev = { git = "https://github.com/virtee/sev", rev = "d487809188c3c92e397bc92e2cb2a85eb982c980", default-features = false, features = [
    "openssl",
    "snp",
    "serde",
] }
wasmtime = { version = "=25.0.3", features = ["component-model"] }
wasmtime-wasi = { version = "=25.0.3" }
wasmtime-wasi-http = { version = "=25.0.3" }
x509-parser = "0.18.0"
