[package]
name = "sgx-verifier-test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
base64.workspace = true
clap.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
wasmtime = { version = "=34.0.2", features = ["component-model"] }
wasmtime-wasi = { version = "=34.0.2" }
wasmtime-wasi-http = { version = "=34.0.2" }
