#!/usr/bin/env python3

"""Generate a TrustMee-aware Rego policy from a standard policy.

The generated policy keeps the original rule structure, but rewrites
TEE-specific claim accesses from:

    input.<tee>.<claim>

to:

    input.<tee>.claims.<claim>

It also injects a TrustMee-specific verifier component hash check for each
detected TEE root:

    input.<tee>.verifier_component_sha256 in
        query_reference_value("<tee>_verifier_component_sha256")
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys


INPUT_ROOT_RE = re.compile(r"\binput\.([A-Za-z_][A-Za-z0-9_]*)\b")
BLOCK_START_RE = re.compile(r"\bif\s*\{")
PROTECTED_ROOTS = {"init_data_claims", "runtime_data_claims"}


def detect_roots(policy: str) -> list[str]:
    roots = set()
    for line in policy.splitlines():
        code, _, _comment = line.partition("#")
        for match in INPUT_ROOT_RE.finditer(code):
            root = match.group(1)
            if root not in PROTECTED_ROOTS:
                roots.add(root)
    return sorted(roots)


def rewrite_claim_paths(policy: str, roots: list[str]) -> str:
    transformed_lines = []

    for line in policy.splitlines(keepends=True):
        code, separator, comment = line.partition("#")
        for root in roots:
            code = re.sub(
                rf"\binput\.{re.escape(root)}(?!\.claims\b)(?=(?:\.[A-Za-z_][A-Za-z0-9_]*|\[|\s|$|[)\]}}]))",
                f"input.{root}.claims",
                code,
            )
        transformed_lines.append(code + separator + comment)

    return "".join(transformed_lines)


def helper_indent(block_lines: list[str]) -> str:
    for line in block_lines[1:]:
        stripped = line.strip()
        if stripped:
            return line[: len(line) - len(line.lstrip())]
    return "\t"


def inject_helper_calls(policy: str, roots: list[str]) -> str:
    lines = policy.splitlines(keepends=True)
    output: list[str] = []
    index = 0

    while index < len(lines):
        line = lines[index]
        if not BLOCK_START_RE.search(line):
            output.append(line)
            index += 1
            continue

        block = [line]
        depth = line.count("{") - line.count("}")
        index += 1

        while index < len(lines) and depth > 0:
            block_line = lines[index]
            block.append(block_line)
            depth += block_line.count("{") - block_line.count("}")
            index += 1

        block_text = "".join(
            line.partition("#")[0]
            for line in block
        )
        roots_in_block = [
            root for root in roots if f"input.{root}.claims" in block_text
        ]
        if not roots_in_block:
            output.extend(block)
            continue

        indent = helper_indent(block)
        helper_lines = [
            f"{indent}trustmee_{root}_verifier_component_ok\n"
            for root in roots_in_block
        ]
        output.append(block[0])
        output.extend(helper_lines)
        output.extend(block[1:])

    return "".join(output)


def helper_section(roots: list[str], source_name: str) -> str:
    lines = [
        f"# Generated by scripts/generate_trustmee_policy.py from {source_name}.",
        "# TrustMee policies keep verifier output nested under `claims` and",
        "# additionally require an approved verifier component hash.",
        "",
    ]

    for root in roots:
        lines.extend(
            [
                f"trustmee_{root}_verifier_component_ok if {{",
                f'\tinput.{root}.verifier_component_sha256 in query_reference_value("{root}_verifier_component_sha256")',
                "}",
                "",
            ]
        )

    return "\n".join(lines).rstrip() + "\n\n"


def insert_helpers(policy: str, roots: list[str], source_name: str) -> str:
    helper_text = helper_section(roots, source_name)
    lines = policy.splitlines(keepends=True)
    insert_at = 0

    for index, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("package ") or stripped.startswith("import ") or not stripped:
            insert_at = index + 1
            continue
        break

    lines.insert(insert_at, helper_text)
    return "".join(lines)


def transform_policy(policy: str, source_name: str) -> str:
    roots = detect_roots(policy)
    transformed = rewrite_claim_paths(policy, roots)
    transformed = inject_helper_calls(transformed, roots)
    return insert_helpers(transformed, roots, source_name)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate a TrustMee-aware Rego policy from a standard policy."
    )
    parser.add_argument("input", type=pathlib.Path, help="Input .rego policy")
    parser.add_argument(
        "-o",
        "--output",
        type=pathlib.Path,
        help="Optional output path. Prints to stdout when omitted.",
    )
    args = parser.parse_args()

    source = args.input.read_text(encoding="utf-8")
    transformed = transform_policy(source, args.input.name)

    if args.output is None:
        sys.stdout.write(transformed)
        return 0

    args.output.write_text(transformed, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
