// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod trustee {
        pub mod verifier {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod verifier_interface {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[derive(Clone)]
                pub enum OptionalData {
                    Value(_rt::Vec<u8>),
                    NotProvided,
                }
                impl ::core::fmt::Debug for OptionalData {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            OptionalData::Value(e) => {
                                f.debug_tuple("OptionalData::Value").field(e).finish()
                            }
                            OptionalData::NotProvided => {
                                f.debug_tuple("OptionalData::NotProvided").finish()
                            }
                        }
                    }
                }
                pub type ReportData = OptionalData;
                pub type InitDataHash = OptionalData;
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct Verifier {
                    handle: _rt::Resource<Verifier>,
                }
                type _VerifierRep<T> = Option<T>;
                impl Verifier {
                    /// Creates a new resource from the specified representation.
                    ///
                    /// This function will create a new resource handle by moving `val` onto
                    /// the heap and then passing that heap pointer to the component model to
                    /// create a handle. The owned handle is then returned as `Verifier`.
                    pub fn new<T: GuestVerifier>(val: T) -> Self {
                        Self::type_guard::<T>();
                        let val: _VerifierRep<T> = Some(val);
                        let ptr: *mut _VerifierRep<T> = _rt::Box::into_raw(
                            _rt::Box::new(val),
                        );
                        unsafe { Self::from_handle(T::_resource_new(ptr.cast())) }
                    }
                    /// Gets access to the underlying `T` which represents this resource.
                    pub fn get<T: GuestVerifier>(&self) -> &T {
                        let ptr = unsafe { &*self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    /// Gets mutable access to the underlying `T` which represents this
                    /// resource.
                    pub fn get_mut<T: GuestVerifier>(&mut self) -> &mut T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_mut().unwrap()
                    }
                    /// Consumes this resource and returns the underlying `T`.
                    pub fn into_inner<T: GuestVerifier>(self) -> T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.take().unwrap()
                    }
                    #[doc(hidden)]
                    pub unsafe fn from_handle(handle: u32) -> Self {
                        Self {
                            handle: unsafe { _rt::Resource::from_handle(handle) },
                        }
                    }
                    #[doc(hidden)]
                    pub fn take_handle(&self) -> u32 {
                        _rt::Resource::take_handle(&self.handle)
                    }
                    #[doc(hidden)]
                    pub fn handle(&self) -> u32 {
                        _rt::Resource::handle(&self.handle)
                    }
                    #[doc(hidden)]
                    fn type_guard<T: 'static>() {
                        use core::any::TypeId;
                        static mut LAST_TYPE: Option<TypeId> = None;
                        unsafe {
                            assert!(! cfg!(target_feature = "atomics"));
                            let id = TypeId::of::<T>();
                            match LAST_TYPE {
                                Some(ty) => {
                                    assert!(
                                        ty == id, "cannot use two types with this resource type"
                                    )
                                }
                                None => LAST_TYPE = Some(id),
                            }
                        }
                    }
                    #[doc(hidden)]
                    pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
                        Self::type_guard::<T>();
                        let _ = unsafe {
                            _rt::Box::from_raw(handle as *mut _VerifierRep<T>)
                        };
                    }
                    fn as_ptr<T: GuestVerifier>(&self) -> *mut _VerifierRep<T> {
                        Verifier::type_guard::<T>();
                        T::_resource_rep(self.handle()).cast()
                    }
                }
                /// A borrowed version of [`Verifier`] which represents a borrowed value
                /// with the lifetime `'a`.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct VerifierBorrow<'a> {
                    rep: *mut u8,
                    _marker: core::marker::PhantomData<&'a Verifier>,
                }
                impl<'a> VerifierBorrow<'a> {
                    #[doc(hidden)]
                    pub unsafe fn lift(rep: usize) -> Self {
                        Self {
                            rep: rep as *mut u8,
                            _marker: core::marker::PhantomData,
                        }
                    }
                    /// Gets access to the underlying `T` in this resource.
                    pub fn get<T: GuestVerifier>(&self) -> &T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    fn as_ptr<T: 'static>(&self) -> *mut _VerifierRep<T> {
                        Verifier::type_guard::<T>();
                        self.rep.cast()
                    }
                }
                unsafe impl _rt::WasmResource for Verifier {
                    #[inline]
                    unsafe fn drop(_handle: u32) {
                        #[cfg(not(target_arch = "wasm32"))]
                        unreachable!();
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]trustee:verifier/verifier-interface"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-drop]verifier"]
                                fn drop(_: u32);
                            }
                            unsafe { drop(_handle) };
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_constructor_verifier_cabi<T: GuestVerifier>() -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = Verifier::new(T::new());
                    (result0).take_handle() as i32
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_verifier_evaluate_cabi<T: GuestVerifier>(
                    arg0: *mut u8,
                    arg1: *mut u8,
                    arg2: usize,
                    arg3: i32,
                    arg4: *mut u8,
                    arg5: usize,
                    arg6: i32,
                    arg7: *mut u8,
                    arg8: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let v2 = match arg3 {
                        0 => {
                            let e2 = {
                                let len1 = arg5;
                                _rt::Vec::from_raw_parts(arg4.cast(), len1, len1)
                            };
                            OptionalData::Value(e2)
                        }
                        n => {
                            debug_assert_eq!(n, 1, "invalid enum discriminant");
                            OptionalData::NotProvided
                        }
                    };
                    let v4 = match arg6 {
                        0 => {
                            let e4 = {
                                let len3 = arg8;
                                _rt::Vec::from_raw_parts(arg7.cast(), len3, len3)
                            };
                            OptionalData::Value(e4)
                        }
                        n => {
                            debug_assert_eq!(n, 1, "invalid enum discriminant");
                            OptionalData::NotProvided
                        }
                    };
                    let result5 = T::evaluate(
                        unsafe { VerifierBorrow::lift(arg0 as u32 as usize) }.get(),
                        _rt::Vec::from_raw_parts(arg1.cast(), len0, len0),
                        v2,
                        v4,
                    );
                    let ptr6 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec7 = (result5.into_bytes()).into_boxed_slice();
                    let ptr7 = vec7.as_ptr().cast::<u8>();
                    let len7 = vec7.len();
                    ::core::mem::forget(vec7);
                    *ptr6.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
                    *ptr6.add(0).cast::<*mut u8>() = ptr7.cast_mut();
                    ptr6
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_verifier_evaluate<T: GuestVerifier>(
                    arg0: *mut u8,
                ) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                pub trait Guest {
                    type Verifier: GuestVerifier;
                }
                pub trait GuestVerifier: 'static {
                    #[doc(hidden)]
                    unsafe fn _resource_new(val: *mut u8) -> u32
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = val;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]trustee:verifier/verifier-interface"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-new]verifier"]
                                fn new(_: *mut u8) -> u32;
                            }
                            unsafe { new(val) }
                        }
                    }
                    #[doc(hidden)]
                    fn _resource_rep(handle: u32) -> *mut u8
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = handle;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]trustee:verifier/verifier-interface"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-rep]verifier"]
                                fn rep(_: u32) -> *mut u8;
                            }
                            unsafe { rep(handle) }
                        }
                    }
                    fn new() -> Self;
                    fn evaluate(
                        &self,
                        evidence: _rt::Vec<u8>,
                        expected_report_data: ReportData,
                        expected_init_data_hash: InitDataHash,
                    ) -> _rt::String;
                }
                #[doc(hidden)]
                macro_rules! __export_trustee_verifier_verifier_interface_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "trustee:verifier/verifier-interface#[constructor]verifier")]
                        unsafe extern "C" fn export_constructor_verifier() -> i32 {
                        unsafe { $($path_to_types)*::
                        _export_constructor_verifier_cabi::<<$ty as $($path_to_types)*::
                        Guest >::Verifier > () } } #[unsafe (export_name =
                        "trustee:verifier/verifier-interface#[method]verifier.evaluate")]
                        unsafe extern "C" fn export_method_verifier_evaluate(arg0 : * mut
                        u8, arg1 : * mut u8, arg2 : usize, arg3 : i32, arg4 : * mut u8,
                        arg5 : usize, arg6 : i32, arg7 : * mut u8, arg8 : usize,) -> *
                        mut u8 { unsafe { $($path_to_types)*::
                        _export_method_verifier_evaluate_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::Verifier > (arg0, arg1, arg2, arg3,
                        arg4, arg5, arg6, arg7, arg8) } } #[unsafe (export_name =
                        "cabi_post_trustee:verifier/verifier-interface#[method]verifier.evaluate")]
                        unsafe extern "C" fn _post_return_method_verifier_evaluate(arg0 :
                        * mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_method_verifier_evaluate::<<$ty as
                        $($path_to_types)*:: Guest >::Verifier > (arg0) } } const _ : ()
                        = { #[doc(hidden)] #[unsafe (export_name =
                        "trustee:verifier/verifier-interface#[dtor]verifier")]
                        #[allow(non_snake_case)] unsafe extern "C" fn dtor(rep : * mut
                        u8) { unsafe { $($path_to_types)*:: Verifier::dtor::< <$ty as
                        $($path_to_types)*:: Guest >::Verifier > (rep) } } }; };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_trustee_verifier_verifier_interface_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 2
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::vec::Vec;
    use core::fmt;
    use core::marker;
    use core::sync::atomic::{AtomicU32, Ordering::Relaxed};
    /// A type which represents a component model resource, either imported or
    /// exported into this component.
    ///
    /// This is a low-level wrapper which handles the lifetime of the resource
    /// (namely this has a destructor). The `T` provided defines the component model
    /// intrinsics that this wrapper uses.
    ///
    /// One of the chief purposes of this type is to provide `Deref` implementations
    /// to access the underlying data when it is owned.
    ///
    /// This type is primarily used in generated code for exported and imported
    /// resources.
    #[repr(transparent)]
    pub struct Resource<T: WasmResource> {
        handle: AtomicU32,
        _marker: marker::PhantomData<T>,
    }
    /// A trait which all wasm resources implement, namely providing the ability to
    /// drop a resource.
    ///
    /// This generally is implemented by generated code, not user-facing code.
    #[allow(clippy::missing_safety_doc)]
    pub unsafe trait WasmResource {
        /// Invokes the `[resource-drop]...` intrinsic.
        unsafe fn drop(handle: u32);
    }
    impl<T: WasmResource> Resource<T> {
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
            debug_assert!(handle != u32::MAX);
            Self {
                handle: AtomicU32::new(handle),
                _marker: marker::PhantomData,
            }
        }
        /// Takes ownership of the handle owned by `resource`.
        ///
        /// Note that this ideally would be `into_handle` taking `Resource<T>` by
        /// ownership. The code generator does not enable that in all situations,
        /// unfortunately, so this is provided instead.
        ///
        /// Also note that `take_handle` is in theory only ever called on values
        /// owned by a generated function. For example a generated function might
        /// take `Resource<T>` as an argument but then call `take_handle` on a
        /// reference to that argument. In that sense the dynamic nature of
        /// `take_handle` should only be exposed internally to generated code, not
        /// to user code.
        #[doc(hidden)]
        pub fn take_handle(resource: &Resource<T>) -> u32 {
            resource.handle.swap(u32::MAX, Relaxed)
        }
        #[doc(hidden)]
        pub fn handle(resource: &Resource<T>) -> u32 {
            resource.handle.load(Relaxed)
        }
    }
    impl<T: WasmResource> fmt::Debug for Resource<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("Resource").field("handle", &self.handle).finish()
        }
    }
    impl<T: WasmResource> Drop for Resource<T> {
        fn drop(&mut self) {
            unsafe {
                match self.handle.load(Relaxed) {
                    u32::MAX => {}
                    other => T::drop(other),
                }
            }
        }
    }
    pub use alloc_crate::boxed::Box;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::string::String;
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_verifier_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::trustee::verifier::verifier_interface::__export_trustee_verifier_verifier_interface_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::trustee::verifier::verifier_interface);
    };
}
#[doc(inline)]
pub(crate) use __export_verifier_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:trustee:verifier:verifier:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 440] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xb9\x02\x01A\x02\x01\
A\x02\x01B\x0c\x01p}\x01q\x02\x05value\x01\0\0\x0cnot-provided\0\0\x04\0\x0dopti\
onal-data\x03\0\x01\x04\0\x0breport-data\x03\0\x02\x04\0\x0einit-data-hash\x03\0\
\x02\x04\0\x08verifier\x03\x01\x01i\x05\x01@\0\0\x06\x04\0\x15[constructor]verif\
ier\x01\x07\x01h\x05\x01@\x04\x04self\x08\x08evidence\0\x14expected-report-data\x03\
\x17expected-init-data-hash\x04\0s\x04\0\x19[method]verifier.evaluate\x01\x09\x04\
\0#trustee:verifier/verifier-interface\x05\0\x04\0\x19trustee:verifier/verifier\x04\
\0\x0b\x0e\x01\0\x08verifier\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0d\
wit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
